name: Terraform Plan with Cost Estimation (Azure)

on:
  push:
    branches:
      - main

jobs:
  terraform:
    name: 'Terraform Plan'
    runs-on: ubuntu-latest

    env:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Terraform Init
        run: terraform init -backend-config="resource_group_name=${{ secrets.BACKEND_RESOURCE_GROUP }}" \
                            -backend-config="storage_account_name=${{ secrets.BACKEND_STORAGE_ACCOUNT }}" \
                            -backend-config="container_name=${{ secrets.BACKEND_CONTAINER_NAME }}" \
                            -backend-config="key=dev/terraform.tfstate"

      - name: Terraform Plan
        run: terraform plan -var-file="terraform.tfvars"

      - name: Print Estimated Cost for Azure DNS (Static Summary)
        run: |
          echo "### 💰 Estimated Azure DNS Cost Summary" >> $GITHUB_STEP_SUMMARY
          echo "- **DNS Zone (Public):** ~ ₹0.50 per zone/month" >> $GITHUB_STEP_SUMMARY
          echo "- **DNS A Record:** Free (included in zone)" >> $GITHUB_STEP_SUMMARY
          echo "- Use Azure Cost Calculator for exact pricing if needed" >> $GITHUB_STEP_SUMMARY


